'use server';
/**
 * @fileOverview An AI ideation tool that generates creative prompts and new ideas based on keywords.
 *
 * - generateCreativePrompts - A function that handles the generation of creative prompts.
 * - GenerateCreativePromptsInput - The input type for the generateCreativePrompts function.
 * - GenerateCreativePromptsOutput - The return type for the generateCreativePrompts function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateCreativePromptsInputSchema = z.object({
  keywords: z
    .array(z.string())
    .describe('A list of keywords to base the creative prompts on.'),
});
export type GenerateCreativePromptsInput = z.infer<
  typeof GenerateCreativePromptsInputSchema
>;

const GenerateCreativePromptsOutputSchema = z.object({
  creativePrompts: z
    .array(z.string())
    .describe('A list of creative prompts or ideas generated by the AI.'),
});
export type GenerateCreativePromptsOutput = z.infer<
  typeof GenerateCreativePromptsOutputSchema
>;

export async function generateCreativePrompts(
  input: GenerateCreativePromptsInput
): Promise<GenerateCreativePromptsOutput> {
  return generateCreativePromptsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateCreativePromptsPrompt',
  input: {schema: GenerateCreativePromptsInputSchema},
  output: {schema: GenerateCreativePromptsOutputSchema},
  prompt: `You are an AI ideation assistant. Your task is to generate creative prompts and new ideas based on the provided keywords.

Generate a list of unique and inspiring prompts that can help a user overcome creative blocks and spark their thought process.

Keywords: {{#each keywords}}- {{{this}}}
{{/each}}

Generate at least 5 creative prompts based on these keywords.`,
});

const generateCreativePromptsFlow = ai.defineFlow(
  {
    name: 'generateCreativePromptsFlow',
    inputSchema: GenerateCreativePromptsInputSchema,
    outputSchema: GenerateCreativePromptsOutputSchema,
  },
  async input => {
    let retries = 3;
    let lastError: any = null;

    while (retries > 0) {
      try {
        const {output} = await prompt(input);
        return output!;
      } catch (err: any) {
        lastError = err;
        const errorMessage = err.message?.toLowerCase() || '';
        const isRetryable = errorMessage.includes('503') || 
                          errorMessage.includes('429') || 
                          errorMessage.includes('quota') || 
                          errorMessage.includes('resource_exhausted') ||
                          errorMessage.includes('high demand');
                          
        if (isRetryable) {
          retries--;
          if (retries > 0) {
            await new Promise(r => setTimeout(r, 2000 * (3 - retries)));
            continue;
          }
        }
        throw err;
      }
    }
    throw lastError;
  }
);
